package com.java.wiki.mapper;

import com.java.wiki.pojo.DemoName;
import com.java.wiki.pojo.DemoNameExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DemoNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    long countByExample(DemoNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int deleteByExample(DemoNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int insert(DemoName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int insertSelective(DemoName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    List<DemoName> selectByExample(DemoNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    DemoName selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByExampleSelective(@Param("record") DemoName record, @Param("example") DemoNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByExample(@Param("record") DemoName record, @Param("example") DemoNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByPrimaryKeySelective(DemoName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByPrimaryKey(DemoName record);
}