package com.java.wiki.mapper;

import com.java.wiki.pojo.EbookName;
import com.java.wiki.pojo.EbookNameExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface EbookNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    long countByExample(EbookNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int deleteByExample(EbookNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int insert(EbookName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int insertSelective(EbookName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    List<EbookName> selectByExample(EbookNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    EbookName selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int updateByExampleSelective(@Param("record") EbookName record, @Param("example") EbookNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int updateByExample(@Param("record") EbookName record, @Param("example") EbookNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int updateByPrimaryKeySelective(EbookName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Mon Mar 04 09:12:44 CST 2024
     */
    int updateByPrimaryKey(EbookName record);
}