package com.java.wiki.mapper;

import com.java.wiki.pojo.TestsName;
import com.java.wiki.pojo.TestsNameExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TestsNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    long countByExample(TestsNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int deleteByExample(TestsNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int insert(TestsName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int insertSelective(TestsName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    List<TestsName> selectByExample(TestsNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    TestsName selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByExampleSelective(@Param("record") TestsName record, @Param("example") TestsNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByExample(@Param("record") TestsName record, @Param("example") TestsNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByPrimaryKeySelective(TestsName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tests
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    int updateByPrimaryKey(TestsName record);
}