package com.java.wiki.pojo;

public class DemoName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}