package com.java.wiki.pojo;

public class TestsName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tests.id
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tests.name
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tests.password
     *
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tests.id
     *
     * @return the value of tests.id
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tests.id
     *
     * @param id the value for tests.id
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tests.name
     *
     * @return the value of tests.name
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tests.name
     *
     * @param name the value for tests.name
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tests.password
     *
     * @return the value of tests.password
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tests.password
     *
     * @param password the value for tests.password
     * @mbg.generated Sun Mar 03 15:53:34 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}